version: '3.5'

services:
  training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
      - imgs:/src/imgs
      - model:/src/model
    container_name: kurkkumopo_training
  backend:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    container_name: kurkkumopo_backend
    depends_on:
      - training
  frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
      - 3000:3000
    container_name: kurkkumopo_frontend
    depends_on:
      - backend

volumes:
  model:
  imgs:
