FROM node:14-alpine3.13 as build-stage

WORKDIR /usr/src/app

COPY . .

RUN npm install && \
    npm run build


FROM node:14-alpine3.13

WORKDIR /usr/src/app

RUN adduser -D appuser && \    
    chown appuser -hR /usr

USER appuser

COPY --from=build-stage /usr/src/app/build ./build

EXPOSE 5000

RUN npm install -g serve

CMD serve -s -l 5000 build